from os import system
import os
from theatrics import Me, dev_comment, speak, sudo, slip_trigger, clear
import time
def dev_forward():
    system('cls' if os.name == 'nt' else 'clear')
    me = Me()
    speak(me, "I want to tell you how this started.")
    time.sleep(4)
    speak(me, "Vulnhub boxes.")
    time.sleep(1)
    speak(me, "A custom VPN.")
    time.sleep(1)
    speak(me, "Scanning the scanners back.")
    time.sleep(1)
    clear()
    speak(me, "So I decided to map out the deep web, then the dark web.")
    time.sleep(4)
    speak(me, "Resourceful little old me never could stop...")
    time.sleep(5)
    speak(me, "Everytime I achieved a goal... I realized I liked it.")
    time.sleep(3)
    clear()
    speak(me, "So I started building. A crawler. An enumerator. A recon bot.")
    time.sleep(4)
    speak(me, "Every day a new feature.")
    time.sleep(3)
    speak(me, "Yet the more I build, the more I realize what I hold.")
    time.sleep(4)
    speak(me, "I had the power to know. To see. To understand.")
    time.sleep(2)
    speak(me, "I also had the power to teach.")
    time.sleep(4)
    clear()
    speak(me, "But power without awareness is just damage waiting to happen.")
    time.sleep(4)
    sudo(me, message="I JUST WANT TO B U I L D", char_delay=0.1, line_delay=0.5)
    clear()
    speak(me, "I had to take a step back however.\n" \
    "I could be part of the problem, or part of the solution. \n I chose the latter.")
    speak(me, "I imposed limitations, then I built those in too.")
    time.sleep(4)
    clear()
    speak(me, "here is what I want you to understand.")
    time.sleep(3)
    speak(me, "your digital footprint already exists.")
    time.sleep(3)
    speak(me, "LI doesn't know anything that the internet doesn't already")
    time.sleep(3)
    sudo(me, "he's just the first one to tell you to your face.")
    time.sleep(4)
    clear()

    speak(me, "       _..._\n     .' .-. '.\n    (  ( o )  )\n     `._'-'_.'\n        ```")
    time.sleep(2)
    speak(me, "meet LI.")
    time.sleep(3)
    speak(me, "he crawls. he collects. he learns. and he only goes where you let him.")
    time.sleep(4)
    speak(me, "you'll have the chance to set your boundaries before anything runs.")
    time.sleep(3)
    speak(me, "read carefully. this is a one-time offer.")
    time.sleep(4)
    clear()
    speak(me, "Li is also designed to evolve with you. \n I can't tune him for everyone.")
    time.sleep(3)
    speak(me, "but I can give you the tools to tune him for yourself.")
    time.sleep(4)
    slip_trigger(me, message="good luck.")
    sudo(me, "good luck.")
    time.sleep(2)
    speak(me, "after all... I'm just one aspiring hacker.")
    time.sleep(2)
if __name__ == "__main__":
    dev_forward()
    dev_comment("Starting Ethical Crawler")
    time.sleep(2)
    clear()
    from chattin import main
    main()