from theatrics import Me, dev_comment
from theatrics import pprint, Me, equip, sudo, pprint 
import time
def dev_forward():
    dev_comment("This repository was named Ethical Boundaries for a reason. It pushes them")   
    time.sleep(3)
    dev_comment("This is not a tool for malicious use. What you do with it is your responsiblity.")
    time.sleep(3)
    dev_comment("It started as a web crawler, then an enumeration program. ")
    time.sleep(3)
    dev_comment("It's become so much more. It's a bot designed to enumerate you, and change itself based on what it sees.")
    me = Me()
    time.sleep(3)
    pprint(me, message="..............................................")    
    dev_comment("Meet LI. LI is a bot. He's designed to crawl, enumerate, and learn all about you. ")
    time.sleep(3)
    dev_comment("Li is also designed to use every ounce of cybersecurity knowledge I have. ")
    time.sleep(3)
    dev_comment("The ethics of this were hard for me to grapple with. I don't want to create something thats intended for harm.") 
    time.sleep(3)   
    dev_comment("What you do with Li now however...thats your responsibility. Not mine")

    time.sleep(3)
    pprint(me, message="..............................................")    
    time.sleep(3)
    dev_comment("I want to create something that pushes the boundaries of what a bot can do.")
    time.sleep(5)
    dev_comment("LI is designed to be a mirror. He reflects back to you what he sees. ")
    time.sleep(3)
    dev_comment("But theres a clause in this")
    time.sleep(3)
    pprint(me, message= "Completeness is not Unity. ")
    dev_comment("When it's done looking at you, thats when your safest. Thats when you'll see exactly what he sees.")   
    time.sleep(3)
    dev_comment("From there you can decide what to do with all that data. Do you delete it? Change it? Use it to your advantage? That's up to you. ")
    time.sleep(5)
    dev_comment("I encourge those who know code to look at what's happening. LI is designed to be transparent.")
    time.sleep(5)   
    dev_comment("When you're done looking at all the data LI collects, and you delete or change it according to your wishes. LI will be like a new slate")
    time.sleep(5)
    dev_comment("Or he'll be exactly as you made him. It's up to you. ")
    time.sleep(5)
    dev_comment("You were warned. Again.")
    time.sleep(5)
    dev_comment("Ethical Boundaries is not a tool for malicious use. What you do with it now is your responsiblity.")
    time.sleep(5)
    pprint(me, message="..............................................")    

if __name__ == "__main__":
    dev_forward()
    dev_comment("Starting Ethical Crawler")
    time.sleep(2)
    from LIMain import main
    main()