from os import system
import os
from theatrics import Me, dev_comment, speak, sudo, slip_trigger, clear, typewriter_effect
import time
# This is the main entry point for the Ethical Crawler. It starts with a little narrative, then launches the chat interface.
#:)
def dev_forward():
    system('cls' if os.name == 'nt' else 'clear')
    me = Me()
    typewriter_effect("I want to tell you how this started.")
    time.sleep(3)
    speak(me, "Vulnhub boxes.")
    time.sleep(1)
    speak(me, "A custom VPN.")
    time.sleep(1)
    speak(me, "Scanning the scanners back.")
    time.sleep(3)
    typewriter_effect("Then I thought\nlets make way\nfor aggressive expansion")
    time.sleep(4)
    clear()
    typewriter_effect("I started mapping out the deep web, then the dark web.")
    time.sleep(4)
    speak(me, "Resourceful little old me never could stop...")
    time.sleep(5)
    speak(me, "Everytime I achieved a goal... I realized I liked every part of the proccess.")
    time.sleep(5)
    clear()
    typewriter_effect("I started building.... A crawler. \nThen an enumerator. \nThen a recon bot.")
    time.sleep(4)
    speak(me,"It spiraled? evolved?")
    time.sleep(3)
    typewriter_effect("the more I build, the more I realize what I can do.")
    time.sleep(4)
    typewriter_effect("I have the power to understand the digital world..")
    time.sleep(2)
    typewriter_effect("I also have the power to teach it.")
    time.sleep(4)
    clear()
    typewriter_effect(  "power without awareness is just damage waiting to happen however.")
    time.sleep(4)
    speak(me, " I JUST WANT TO B U I L D  ")
    time.sleep(2) #idk if i want sudo..
    clear()
    typewriter_effect("So I took a step back\n" \
    "I could be part of the problem\nI could be part of the solution.")
    speak(me, "I chose them both..")
    time.sleep(4)
    typewriter_effect("I imposed limitations, then I baked them into the code.")
    time.sleep(4)
    clear()
    typewriter_effect("here is what I want you to understand.")
    time.sleep(3)
    typewriter_effect("your digital footprint already exists.")
    time.sleep(3)
    typewriter_effect("This code doesn't know anything that the internet doesn't already")
    time.sleep(3)
    speak(me, "I'm just the first one to tell you to your face.")
    time.sleep(4)
    clear()
    typewriter_effect("       _..._\n     .' .-. '.\n    (  ( o )  )\n     `._'-'_.'\n        ```")
    time.sleep(2)
    typewriter_effect("meet LI.")
    time.sleep(3)
    typewriter_effect("he crawls. \nhe collects. \nhe learns. \nhe only goes where you let him.")
    time.sleep(4)
    typewriter_effect("you'll have the chance to set your boundaries before anything runs.")
    time.sleep(4)
    clear()
    typewriter_effect("Li is also designed to evolve with you. \nI can't tune him for everyone.")
    time.sleep(3)
    typewriter_effect("but I can give you the tools to tune him for yourself.")
    time.sleep(4)
    speak(me, "good luck.")
    time.sleep(2)
    speak(me, "after all... I'm just one aspiring hacker.")
    time.sleep(2)
if __name__ == "__main__":
    dev_forward()
    dev_comment("Starting Ethical Crawler")
    time.sleep(2)
    clear()
    from chattin import main
    main()